// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeerpalKaurBookStore.DataAccess.Data;

namespace VeerpalBooks.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231120213543_addProductToDb")]
    partial class addProductToDb : addProductToDbBase
    {
    }

    internal class addProductToDbBase
    {
    }
}
